import type { Metadata } from "next";
import AppBar from "@/components/app-bar";
import Footer from "@/components/footer";
import { Noto_Serif } from "next/font/google";
import "./globals.css";

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${notoSerif.variable} h-full antialiased`}>
      <body className="font-serif min-h-full flex flex-col">
        <AppBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
